#!/usr/bin/env bash
# Read the file /etc/passwd line by line using while loop
while IFS=':' read -r username password  userid groupid info homedir shell; do
    user_info=$(getent passwd "$username")
    passcode=$(echo "$user_info" | cut -d ':' -f 2)
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
