#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for file in *; do
    if [ ! -f "$file" ] || [[ "$file" == .* ]] || [[ ! "$file" =~ "-" ]]; then
        continue
    fi

    name=$(echo "$file" | cut -d'-' -f2-)
    
    echo "$name"
done
